# Generated by Django 3.0.10 on 2021-02-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='asset_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='transport.AssetStore'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='scheduler.Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='asset_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transport.AssetStore'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scheduler.Folder'),
        ),
        migrations.AddField(
            model_name='conceptualmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptualmodels', to='scheduler.Project'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL),
        ),
    ]
