# Generated by Django 3.0.10 on 2020-12-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_give_admin_project', 'Can give others full access'), ('can_give_transferable_admin_project', 'Can give others transferable full access')]},
        ),
    ]
