# Generated by Django 3.0.10 on 2020-12-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201210_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_give_admin_project', 'Can give others full access'), ('can_remove_admin_project', 'Can revoke full access'), ('can_give_transferable_admin_project', 'Can give others transferable full access'), ('can_remove_transferable_admin_project', 'Can revoke transferable full access')]},
        ),
    ]
