# Generated by Django 3.0.10 on 2021-02-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210210_1035'),
        ('transport', '0002_auto_20210210_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputFile',
        ),
        migrations.DeleteModel(
            name='OutputFile',
        ),
        migrations.DeleteModel(
            name='SimulationFile',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='scheduler.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='scheduler.Project'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scheduler.Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scheduler.Project'),
        ),
    ]
