# Generated by Django 3.0.10 on 2021-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_simulation_output_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='abs_path',
            field=models.CharField(default='temporary_path', max_length=255),
            preserve_default=False,
        ),
    ]
