# Generated by Django 3.0.10 on 2021-02-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210210_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='project',
        ),
    ]
