# Generated by Django 3.0.10 on 2020-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='public_key',
            field=models.CharField(default='default_key_for_migrations', max_length=4096, verbose_name='Public key for ssh connection'),
            preserve_default=False,
        ),
    ]
