# Generated by Django 3.0.10 on 2020-10-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        ('scheduler', '0011_cluster_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='public_key',
        ),
        migrations.AddField(
            model_name='cluster',
            name='ssh_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.SSHConnectionInfo'),
        ),
    ]
