# Generated by Django 3.0.10 on 2020-11-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20201030_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='ssh_info',
        ),
    ]
