# Generated by Django 3.0.10 on 2020-11-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_remove_cluster_ssh_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='hostname',
            field=models.CharField(default='default_hostname', max_length=253, verbose_name='Hostname'),
            preserve_default=False,
        ),
    ]
