# Generated by Django 3.0.10 on 2021-02-17 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name of Key Pair')),
                ('public_key', models.TextField(null=True, verbose_name='Public key for ssh connection')),
                ('private_key_encrypted', models.TextField(null=True, verbose_name='Encrypted private key for ssh connection')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_pairs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorizedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Username for cluster user')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to='scheduler.Cluster')),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to='transport.KeyPair')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_stores', to='scheduler.Cluster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_stores', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_stores', to='scheduler.Simulation')),
            ],
        ),
    ]
