# Generated by Django 3.0.10 on 2020-11-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0001_initial'),
        ('scheduler', '0002_auto_20201120_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypair',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorizedkey',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to='scheduler.Cluster'),
        ),
        migrations.AddField(
            model_name='authorizedkey',
            name='key_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to='transport.KeyPair'),
        ),
    ]
