# Generated by Django 3.0.10 on 2020-11-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_remove_cluster_ssh_info'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshconnectioninfo',
            name='key_pair',
        ),
        migrations.RemoveField(
            model_name='sshconnectioninfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='KeyPair',
        ),
        migrations.DeleteModel(
            name='SSHConnectionInfo',
        ),
    ]
