# Generated by Django 3.0.10 on 2021-02-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210210_1035'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstore',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='assetstore',
            name='outputs',
        ),
        migrations.AddField(
            model_name='assetstore',
            name='ingested_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_stores', to='scheduler.Folder'),
        ),
    ]
