# Generated by Django 3.0.10 on 2021-02-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20210210_1042'),
        ('transport', '0002_auto_20210210_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstore',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_stores', to='scheduler.Simulation'),
        ),
    ]
