# Generated by Django 3.0.10 on 2020-11-10 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_keypair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='private_key_encrypted',
            field=models.CharField(max_length=4096, null=True, verbose_name='Encrypted private key for ssh connection'),
        ),
        migrations.AlterField(
            model_name='keypair',
            name='public_key',
            field=models.CharField(max_length=4096, null=True, verbose_name='Public key for ssh connection'),
        ),
    ]
