# Generated by Django 3.0.10 on 2021-02-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20210217_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetstore',
            name='simulation',
        ),
    ]
