# Generated by Django 3.0.10 on 2020-11-12 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_cluster_hostname'),
        ('transport', '0004_auto_20201110_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=4096, verbose_name='Public key for cluster')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_keys', to='scheduler.Cluster')),
            ],
        ),
    ]
